version: '3.8'

services:
  app:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: database
      DATABASE_USERNAME: user
      DATABASE_SECRET: password
      DATABASE_PORT: 5432
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
